services:
  db:
    image: postgres:13
    restart: always
    container_name: prisma
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpw
      POSTGRES_DB: db
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  test-db:
    image: postgres:13
    restart: always
    container_name: test-prisma
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpw
      POSTGRES_DB: test-db

volumes:
  postgres:
